<?php

namespace App\Http\Controllers;

use App\Exceptions\TranslationException;
use App\Jobs\TranslateDocumentJob;
use App\Services\HistoryService;
use App\Services\StorageService;
use App\Services\Translation\TranslationManager;
use App\Support\ReviewStatus;
use App\Services\Translation\DTO\TranslationRequest;
use App\Services\Translation\DTO\TranslationResponse;
use App\Services\TranslationService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class TranslationController extends Controller
{
    public function __construct(
        private TranslationManager $translationManager,
        private StorageService $storage,
        private HistoryService $history,
    ) {}

    /**
     * GET /translate — render the translation page.
     */
    public function show(): View
    {
        return view('translation');
    }

    /**
     * POST /translate — handle text or document translation.
     * Documents are dispatched to queue for async processing.
     */
    public function translate(Request $request): JsonResponse
    {
        $sourceLang = $request->input('source_lang');

        // Validate basic fields
        $validated = $request->validate([
            'source_lang' => ['required', Rule::in(['English', 'Cebuano', 'Filipino'])],
            'target_lang' => [
                'required',
                Rule::in(['English', 'Cebuano', 'Filipino']),
                Rule::notIn([$sourceLang]),
            ],
            'text'     => ['nullable', 'string', 'max:8000'],
            'document' => ['nullable', 'file', 'mimes:docx,pdf,txt,md,rtf,odt,csv,pptx,xlsx', 'max:51200'],
            'pdf_column_mode' => ['nullable', Rule::in(['auto', 'single', 'left', 'right'])],
            'mode' => ['nullable', Rule::in(['fast', 'balanced', 'thorough', 'auto'])],
        ], [
            'target_lang.not_in' => 'The source language and target language must be different.',
        ]);

        $targetLang = $validated['target_lang'];
        $pdfColumnMode = $validated['pdf_column_mode'] ?? 'auto';

        // Manual validation: ensure either text or document is provided
        $hasText = !empty($validated['text']);
        $hasDocument = $request->hasFile('document');

        if (!$hasText && !$hasDocument) {
            return response()->json([
                'error' => 'Please enter text to translate or attach a document.',
                'errors' => [
                    'text' => ['The text field is required when document is not present.'],
                ]
            ], 422);
        }

        try {
            // Document mode — dispatch to queue for async processing
            if ($request->hasFile('document')) {
                $uploadedFile = $request->file('document');
                $originalName = $uploadedFile->getClientOriginalName();
                $originalExt  = strtolower('.' . $uploadedFile->getClientOriginalExtension());
                $fileSize     = $uploadedFile->getSize();

                // 1. Upload the ORIGINAL file to Supabase Storage
                $originalStoragePath = Auth::id() . '/originals/' . Str::uuid() . '_' . $originalName;

                try {
                    $this->storage->uploadFile(
                        $uploadedFile->getRealPath(),
                        $originalStoragePath
                    );
                } catch (\Throwable $e) {
                    Log::warning('Supabase Storage upload failed for original file (translation will still proceed)', [
                        'exception' => $e->getMessage(),
                        'storage_path' => $originalStoragePath,
                    ]);
                    // Mark the original as not stored — translation can still proceed
                    $originalStoragePath = null;
                }

                // 2. Dispatch job to queue
                // Get the UUID generated by the Dispatchable trait for cache key consistency
                $mode = $request->input('mode', 'balanced');
                $job = new TranslateDocumentJob(
                    $originalName,
                    $originalExt,
                    $fileSize,
                    $sourceLang,
                    $targetLang,
                    $pdfColumnMode,
                    $uploadedFile->getRealPath(),
                    Auth::id(),
                    $originalStoragePath,
                    $mode
                );
                $jobId = $job->uuid();

                dispatch($job);

                // 4. Return job ID for polling
                return response()->json([
                    'job_id' => $jobId,
                    'status' => 'processing',
                    'message' => 'Document queued for translation. Processing will begin shortly.',
                    'original_filename' => $originalName,
                ]);
            }

            // Text mode — process synchronously (fast enough)
            $translationRequest = new TranslationRequest(
                text: $request->input('text'),
                sourceLang: $sourceLang,
                targetLang: $targetLang,
            );
            $result = $this->translationManager->translateText($translationRequest);

            // Log text translation to history (non-blocking)
            try {
                $this->history->insertRecord([
                    'user_id'          => Auth::id(),
                    'translation_type' => 'text',
                    'source_text'      => $request->input('text'),
                    'translated_text'  => $result->translatedText,
                    'source_language'  => $sourceLang,
                    'target_language'  => $targetLang,
                    'created_at'       => now()->toIso8601String(),
                    'status'           => 'completed',
                    'review_status'    => ReviewStatus::PENDING,
                ]);
            } catch (\Throwable $e) {
                Log::error('Failed to insert text translation history record', [
                    'exception'  => $e->getMessage(),
                    'user_id'    => Auth::id(),
                ]);
            }

            return response()->json(['translated' => $result->translatedText]);

        } catch (TranslationException $e) {
            $message = $e->getMessage();
            $code = $e->getCode() ?: 500;

            Log::error('Translation service error', [
                'exception' => $message,
                'code' => $code,
                'user_id' => Auth::id(),
            ]);

            // User-friendly error messages based on error type
            if (str_contains($message, 'timed out')) {
                return response()->json([
                    'error' => 'Translation timed out. The document may be too large or complex. Try a smaller file or simpler content, and we will try again.',
                    'retryable' => true,
                ], 504);
            }

            if (str_contains($message, 'Could not connect')) {
                return response()->json([
                    'error' => 'The translation service is temporarily unavailable. Please try again in a moment or contact support if the issue persists.',
                    'retryable' => true,
                ], 503);
            }

            if ($code === 400) {
                return response()->json(['error' => $message], 400);
            }

            return response()->json([
                'error' => $message ?: 'Translation failed. Please try again or contact support if the problem persists.',
                'retryable' => true,
            ], $code);
        } catch (\Throwable $e) {
            Log::error('Unexpected error in translation controller', [
                'exception' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'user_id' => Auth::id(),
            ]);

            return response()->json([
                'error' => 'An unexpected error occurred during translation. Please try again. If the problem continues, contact support.',
                'retryable' => true,
            ], 500);
        }
    }

    /**
     * GET /translate/status/{job_id} — poll for document translation status
     */
    public function status(string $jobId): JsonResponse
    {
        $result = Cache::get('translation_job_' . $jobId);

        if (!$result) {
            return response()->json([
                'status' => 'processing',
                'message' => 'Translation is still in progress...',
            ]);
        }

        return response()->json($result);
    }

    private function buildInlineDownloadPayload(string $outputPath, string $downloadFilename): array
    {
        $contents = @file_get_contents($outputPath);
        $mimeType = mime_content_type($outputPath) ?: 'application/octet-stream';

        if ($contents === false || $contents === '') {
            return [
                'download_filename' => $downloadFilename,
                'download_data'     => '',
                'download_mime'     => $mimeType,
            ];
        }

        return [
            'download_filename' => $downloadFilename,
            'download_data'     => 'data:' . $mimeType . ';base64,' . base64_encode($contents),
            'download_mime'     => $mimeType,
        ];
    }

}
