# -*- coding: utf-8 -*-
"""
AI Layout Planner.

Predicts layout adjustments BEFORE reconstruction. This does NOT replace
the existing deterministic reconstructor — it only provides recommendations
that the reconstructor MAY use.

The planner estimates:
- Text expansion/shrinkage ratios
- Page overflow risk
- Font scaling recommendations
- Paragraph growth predictions
- Table expansion estimates

Initially enabled ONLY for PDF. DOCX/PPTX/XLSX continue using the existing
deterministic in-place translators which already handle layout perfectly.

The existing _resolve_overflow function in reconstructor.py already handles
overflow situations with 3 strategies (expand rect, reduce font, continuation box).
The LayoutPlan provides EARLY WARNING so the reconstructor can make better
decisions about which strategy to use.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class BlockAdjustment:
    """A layout adjustment recommendation for a single block."""
    block_index: int
    estimated_expansion_ratio: float     # e.g., 1.2 = 20% longer text
    recommended_font_scale: float        # e.g., 0.95 = shrink 5%
    overflow_risk: str                   # "none", "low", "medium", "high"
    suggested_height_extra: float = 0.0  # Extra height needed (points)
    continuation_needed: bool = False    # Whether overflow continuation is likely
    alignment_override: str | None = None   # "left", "center", "right", "justify", or None
    indent_override: float | None = None    # Left indent in points, or None
    font_override: str | None = None        # Suggested font name, or None
    paragraph_spacing: float | None = None  # Extra spacing after block (points), or None


@dataclass
class PageBreak:
    """A predicted page break."""
    page_number: int
    expected_overflow: bool


@dataclass
class LayoutPlan:
    """Complete layout plan for a document.

    This is a PREDICTION, not a command. The existing deterministic
    reconstructor makes the final decisions. The plan provides hints
    about what to expect.
    """
    adjustments: list[BlockAdjustment] = field(default_factory=list)
    page_breaks: list[PageBreak] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    # Overall statistics
    estimated_total_expansion: float = 0.0  # Overall text growth ratio
    high_risk_blocks: int = 0
    medium_risk_blocks: int = 0

    # Whether the plan was generated by AI or heuristics
    generated_by: str = "heuristic"  # "ai" or "heuristic"


class LayoutPlanner:
    """Predicts layout adjustments for translated documents.

    Uses AI analysis for accurate expansion predictions.
    Falls back to heuristic estimates if AI is unavailable.

    The planner does NOT modify any documents. It only produces a plan.
    """

    # Language pair expansion ratios (source -> target)
    # These are heuristic fallbacks when AI is not available
    HEURISTIC_EXPANSION: dict[tuple[str, str], float] = {
        ("English", "Cebuano"): 0.85,    # Cebuano is more concise
        ("English", "Filipino"): 1.15,   # Filipino is slightly longer
        ("English", "Spanish"): 1.20,    # Spanish is typically longer
        ("English", "French"): 1.15,
        ("English", "German"): 1.10,
        ("English", "Japanese"): 0.80,   # Japanese is more compact
        ("English", "Chinese"): 0.75,
    }

    DEFAULT_EXPANSION = 1.10  # Default: 10% expansion

    # Thresholds for overflow risk classification
    LOW_RISK_THRESHOLD = 1.15
    MEDIUM_RISK_THRESHOLD = 1.30
    HIGH_RISK_THRESHOLD = 1.50

    def __init__(self, ai_provider=None):
        """Initialize the layout planner.

        Args:
            ai_provider: Optional AIAnalysisProvider for AI-powered predictions.
                         If None, uses heuristic estimates only.
        """
        self._ai = ai_provider

    def plan(self, blocks: list[dict], translated_blocks: list[dict] | None = None,
             source_lang: str = "", target_lang: str = "",
             doc_format: str = "", document_type: str = "") -> LayoutPlan:
        """Generate a layout plan for a translated document.

        Args:
            blocks: Original source blocks.
            translated_blocks: Optional translated blocks (if available).
            source_lang: Source language name.
            target_lang: Target language name.
            doc_format: Document format ('pdf', 'docx', etc.).
            document_type: Document type (from analyzer).

        Returns:
            A LayoutPlan with predictions and recommendations.
        """
        import time as _time
        start = _time.time()

        plan = LayoutPlan()
        plan.generated_by = "heuristic"

        # Only plan for PDF initially
        if doc_format != "pdf":
            return plan

        # Use heuristic expansion ratios
        expansion_ratio = self._get_expansion_ratio(source_lang, target_lang)

        # Analyze each block
        high_risk = 0
        medium_risk = 0

        for i, block in enumerate(blocks):
            text = block.get("text", "")
            if not text.strip():
                continue

            # Estimate expansion for this block
            block_ratio = self._estimate_block_expansion(
                block, expansion_ratio, document_type
            )

            # Determine overflow risk
            risk = self._classify_risk(block_ratio)
            if risk == "high":
                high_risk += 1
            elif risk == "medium":
                medium_risk += 1

            # Calculate suggested height extra
            original_len = len(text.split())
            extra_chars = int(original_len * (block_ratio - 1))
            height_extra = max(0, extra_chars * 0.5)  # Rough estimate: 0.5pt per character

            # Extract alignment from block metadata (set by extractor B1)
            block_alignment = block.get("alignment", "left")

            adjustment = BlockAdjustment(
                block_index=i,
                estimated_expansion_ratio=round(block_ratio, 2),
                recommended_font_scale=round(min(1.0, 1.0 / block_ratio), 2)
                if block_ratio > 1.2 else 1.0,
                overflow_risk=risk,
                suggested_height_extra=round(height_extra, 1),
                continuation_needed=risk in ("high", "medium"),
                alignment_override=block_alignment,
            )

            plan.adjustments.append(adjustment)

            # Add warnings for high-risk blocks
            if risk == "high":
                plan.warnings.append(
                    f"Block {i} (type: {block.get('type', 'unknown')}): "
                    f"High overflow risk ({block_ratio:.2f}x expansion estimated)"
                )

        plan.high_risk_blocks = high_risk
        plan.medium_risk_blocks = medium_risk
        plan.estimated_total_expansion = round(expansion_ratio, 2)

        # Try AI-powered analysis if available and there are high-risk blocks
        if self._ai and (high_risk > 0 or medium_risk > 2):
            ai_plan = self._ai_layout_plan(blocks, translated_blocks, source_lang, target_lang, document_type)
            if ai_plan is not None:
                plan = ai_plan

        elapsed = (_time.time() - start) * 1000
        print(f"  [LayoutPlanner] Plan generated in {elapsed:.0f}ms "
              f"(expansion: {plan.estimated_total_expansion:.2f}x, "
              f"high risk: {plan.high_risk_blocks}, "
              f"method: {plan.generated_by})")

        return plan

    def _get_expansion_ratio(self, source_lang: str, target_lang: str) -> float:
        """Get heuristic expansion ratio for a language pair."""
        key = (source_lang, target_lang)
        return self.HEURISTIC_EXPANSION.get(key, self.DEFAULT_EXPANSION)

    def _estimate_block_expansion(self, block: dict,
                                   base_ratio: float,
                                   document_type: str) -> float:
        """Estimate expansion ratio for a specific block.

        Different block types may expand differently.
        Headers/footers typically have less text and expand less.
        Table cells with numbers expand minimally.
        Paragraphs with long sentences expand more.
        """
        block_type = block.get("type", "paragraph")
        text = block.get("text", "")

        # Short text blocks expand less (less room for rephrasing)
        word_count = len(text.split())
        if word_count < 5:
            return base_ratio * 0.8

        # Headers and footers — typically shorter
        if block_type in ("header", "footer", "heading"):
            return base_ratio * 0.9

        # Table cells with numbers — minimal expansion
        if block_type == "table_cell":
            import re
            if re.search(r'\d', text):
                return base_ratio * 0.85

        # Lists — items tend to stay similar length
        if block_type == "list_item":
            return base_ratio * 0.95

        return base_ratio

    def _classify_risk(self, ratio: float) -> str:
        """Classify overflow risk based on expansion ratio."""
        if ratio >= self.HIGH_RISK_THRESHOLD:
            return "high"
        elif ratio >= self.MEDIUM_RISK_THRESHOLD:
            return "medium"
        elif ratio >= self.LOW_RISK_THRESHOLD:
            return "low"
        return "none"

    def _ai_layout_plan(self, blocks: list[dict],
                         translated_blocks: list[dict] | None,
                         source_lang: str, target_lang: str,
                         document_type: str) -> LayoutPlan | None:
        """Generate a layout plan using AI analysis with per-block layout rules.

        Falls back to heuristic plan if AI is unavailable or fails.
        """
        if not self._ai:
            return None

        try:
            # Build block pairs with source text, translated text, and metadata
            block_pairs = []
            for i, block in enumerate(blocks):
                src_text = block.get("text", "")
                tgt_text = src_text
                if translated_blocks and i < len(translated_blocks):
                    tgt_text = translated_blocks[i].get("text", src_text)
                block_pairs.append({
                    "index": i,
                    "type": block.get("type", "paragraph"),
                    "alignment": block.get("alignment", "left"),
                    "source": src_text[:200],
                    "translated": tgt_text[:200],
                })

            system_prompt = (
                "You are a document layout analyst. Given document blocks with "
                "source and translated text, recommend layout adjustments.\n\n"
                "Return JSON:\n"
                "{\n"
                '  "blocks": [\n'
                '    {\n'
                '      "index": 0,\n'
                '      "estimated_expansion_ratio": 1.15,\n'
                '      "overflow_risk": "medium",\n'
                '      "alignment_override": "left",\n'
                '      "indent_override": 0.0,\n'
                '      "font_override": null,\n'
                '      "paragraph_spacing": null\n'
                '    }\n'
                '  ],\n'
                '  "overall_expansion_ratio": 1.1,\n'
                '  "warnings": []\n'
                "}\n\n"
                "Rules:\n"
                '- alignment_override: "left", "center", "right", "justify", or null (no change)\n'
                "- indent_override: left indent in points, or null (no change)\n"
                '- font_override: font name suggestion or null (keep existing)\n'
                "- paragraph_spacing: extra spacing after block in points, or null (keep existing)\n"
                "- estimated_expansion_ratio: >1.0 if translated is longer, <1.0 if shorter\n"
                '- overflow_risk: "none", "low", "medium", "high"\n'
                "Return ONLY valid JSON."
            )

            user_prompt = (
                f"Document type: {document_type}\n"
                f"Source: {source_lang} → Target: {target_lang}\n\n"
                f"Blocks:\n{block_pairs}\n\n"
                f"Recommend per-block layout adjustments."
            )

            result = self._ai.analyze(system_prompt, user_prompt)

            # Parse AI response
            plan = LayoutPlan()
            plan.generated_by = "ai"

            ai_blocks = result.get("blocks", [])
            if isinstance(ai_blocks, list):
                for b in ai_blocks:
                    if isinstance(b, dict):
                        plan.adjustments.append(BlockAdjustment(
                            block_index=int(b.get("index", 0)),
                            estimated_expansion_ratio=float(
                                b.get("estimated_expansion_ratio", 1.0)
                            ),
                            recommended_font_scale=1.0,
                            overflow_risk=str(b.get("overflow_risk", "none")),
                            alignment_override=b.get("alignment_override"),
                            indent_override=(
                                float(b["indent_override"])
                                if b.get("indent_override") is not None
                                else None
                            ),
                            font_override=b.get("font_override"),
                            paragraph_spacing=(
                                float(b["paragraph_spacing"])
                                if b.get("paragraph_spacing") is not None
                                else None
                            ),
                        ))

            plan.estimated_total_expansion = float(
                result.get("overall_expansion_ratio", 1.0)
            )
            plan.warnings = result.get("warnings", [])

            # Count risks
            for adj in plan.adjustments:
                if adj.overflow_risk == "high":
                    plan.high_risk_blocks += 1
                elif adj.overflow_risk == "medium":
                    plan.medium_risk_blocks += 1

            return plan

        except (RuntimeError, ConnectionError, Exception) as e:
            print(f"  [LayoutPlanner] AI planning failed: {e}")
            print(f"  [LayoutPlanner] Falling back to heuristic plan")
            return None

    def get_font_scale(self, block_index: int, plan: LayoutPlan | None) -> float:
        """Get recommended font scale for a block from the plan.

        Args:
            block_index: Block index to look up.
            plan: The layout plan (may be None).

        Returns:
            Recommended font scale (1.0 = no change).
        """
        if plan is None:
            return 1.0

        for adj in plan.adjustments:
            if adj.block_index == block_index:
                return adj.recommended_font_scale

        return 1.0

    def get_overflow_risk(self, block_index: int,
                           plan: LayoutPlan | None) -> str:
        """Get overflow risk for a block from the plan."""
        if plan is None:
            return "none"

        for adj in plan.adjustments:
            if adj.block_index == block_index:
                return adj.overflow_risk

        return "none"